;the user interface has the function ProcessKey in it, which uses the following
;key values

KEY_SER                 EQU     28H
KEY_ENTER               EQU     08H
KEY_PLUS_MINUS          EQU     01H
KEY_0                   EQU     02H
KEY_1                   EQU     11H
KEY_2                   EQU     12H
KEY_3                   EQU     14H
KEY_4                   EQU     21H
KEY_5                   EQU     22H
KEY_6                   EQU     24H
KEY_7                   EQU     31H
KEY_8                   EQU     32H
KEY_9                   EQU     34H
KEY_CLEAR               EQU     38H
KEY_STEP		EQU	18H
KEY_PATH                EQU     04H

;
MAIN_MENU		EQU	0
SER_MENU		EQU	1
PATH_MENU		EQU	2
STEP_MENU		EQU	3
PARITY_MENU		EQU	4
BR_MENU		EQU	5

PATH_SIZE		EQU	255

